# Change these first
owner: jerm # Your GitHub username
repo: uptime # Your GitHub repository name

# Add your sites here
sites:
  - name: Jermops Blog
    url: https://jermops.com/
  #- name: Secret Site
  #  url: $SECRET_SITE

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.jerm.dev
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Jermops Uptime Thing
  introTitle: "Jermops stuff status"
  introMessage: isitdownorjustme?
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
